import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Finance Budget App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <>
          <h1>Home Page</h1>
        </>
      </main>
    </div>
  );
}
